2023-06-29 10:56:14,503 ERROR Any error
Traceback (most recent call last):
  File "/tmp/ipykernel_13477/3414978077.py", line 17, in outside_exception
    "hello" + 7
TypeError: can only concatenate str (not "int") to str
2023-06-29 10:56:20,079 ERROR Any error
Traceback (most recent call last):
  File "/tmp/ipykernel_13477/3182015258.py", line 22, in <module>
    fun()
  File "/tmp/ipykernel_13477/3182015258.py", line 3, in <lambda>
    lambda: 7/0, # ZeroDivisionError
ZeroDivisionError: division by zero
2023-06-29 10:56:20,079 ERROR Any error
Traceback (most recent call last):
  File "/tmp/ipykernel_13477/3182015258.py", line 22, in <module>
    fun()
  File "/tmp/ipykernel_13477/3182015258.py", line 4, in <lambda>
    lambda: "hello" + 5784 # TypeError
TypeError: can only concatenate str (not "int") to str
