2023-06-29 09:32:41,308 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "/tmp/ipykernel_7485/2347500040.py", line 11, in <module>
    7/0
ZeroDivisionError: division by zero
